version: "3.8"

services:
  redis:
    image: redis
    container_name: cache
    restart: always
    ports:
      - '6379:6379'
  app:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - redis
    environment:
      - REDIS_EX=300
      - PORT=5000
      - REDIS_URL=redis://cache